services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.1
    ports:
      - "8081:8080"
      - "50051:50051"
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      QUERY_DEFAULTS_LIMIT: 10
      ENABLE_MODULES: ""
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: 'node1'
volumes:
  weaviate_data:


